---
CoreConfig:           # Core configuration settings for the run.
  TC_Iterations: 10  # Number of times to form and teradown the IPsec tunnel, per TC setting.
  MaxTimeS: 36000      # Maximum time to run the test in seconds.
  LocalPath: "../../"      # Local path to copy the logs to.
  RemotePath: "/var/log/charon.log"   # Remote path to copy the log file from.
  WiresharkLogs: false        # Capture Wireshark logs from Carol. 
  WSRemotePath: "/var/log/"   # Remote path to copy the Wireshark logs from.
  WSLocalPath: "/"            # Local path to copy the Wireshark logs to.
  MirrorMoon: false           # Do not Mirror the Carol's TC settings to Moon.
  PrintLevel: 1               # Information Display Level for the run.
  compose_files: "../pq-strongswan/docker-compose.yml"  # Docker compose file location
  Note: "PQ"
Carol_TC_Config:  # Carol's Traffic Control settings.
  Constraint1:        # Constraint 1, this is the adjustable constraint.
    Type: netem         # Type of constraint, netem for network emulation.
    Constraint: delay   # Constraint to adjust, delay in this case.
    Interface: eth0     # Interface to apply the constraint to.
    StartRange: 1       # Start range of the constraint.
    EndRange: 200       # End range of the constraint.
    Units: ms           # Units of the constraint.
    Steps: 2            # Number of steps to take between the start and end range.
    AddParams: ''       # Additional parameters to add to the constraint. EG: 'loss 0.1%'
  Constraint2:    # Constraint 2, this NOT adjustable. 
    Type: netem   # IF the type matches Constraint 1, it will be placed in AddParams for constraint 1.
    Constraint: loss    # Constraint to add, loss in this case
    Interface: eth0     # Interface to apply the constraint to.
    StartRange: 0.1     # Value to set for the constraint.
    Units: "%"          # Units of the constraint, percentage in this case.
    Steps: 1            # This is ignored as "additional" constraints are not adjustable.
    AddParams: ''       # Additional parameters to add to the constraint. EG: 'delay 100ms'
Moon_TC_Config:   # Moon's Traffic Control settings.
  Constraint1:        # Constraint 1, this is not an adjustable constraint.
    Type: netem
    Constraint: delay
    Interface: eth0
    StartRange: 1
    EndRange: 1000
    Units: ms
    Steps: 1
    AddParams: ''