---
CoreConfig:           # Core configuration settings for the run.
  TC_Iterations: 1000  # Number of times to form and teradown the IPsec tunnel, per TC setting.
  MaxTimeS: 36000      # Maximum time to run the test in seconds.
  LocalPath: "../../"      # Local path to copy the logs to.
  RemotePath: "/var/log/charon.log"   # Remote path to copy the log file from.
  WiresharkLogs: false        # Capture Wireshark logs from Carol. 
  WSRemotePath: "/var/log/"   # Remote path to copy the Wireshark logs from.
  WSLocalPath: "/"            # Local path to copy the Wireshark logs to.
  MirrorMoon: false           # Do not Mirror the Carol's TC settings to Moon.
  PrintLevel: 1               # Information Display Level for the run.
  compose_files: "../pq-strongswan/docker-compose.yml"  # Docker compose file location
  Note: "DH"
