---
CoreConfig:           # Core configuration settings for the run.
  TC_Iterations: 10  # Number of times to form and teradown the IPsec tunnel, per TC setting.
  MaxTimeS: 72000      # Maximum time to run the test in seconds.
  LocalPath: "../../baseline_"      # Local path to copy the logs to.
  RemotePath: "/var/log/charon.log"   # Remote path to copy the log file from.
  WiresharkLogs: false        # Capture Wireshark logs from Carol. 
  WSRemotePath: "/var/log/"   # Remote path to copy the Wireshark logs from.
  WSLocalPath: "/"            # Local path to copy the Wireshark logs to.
  MirrorMoon: false           # Do not Mirror the Carol's TC settings to Moon.
  PrintLevel: 2               # Information Display Level for the run.
  compose_files: "./pq-strongswan/baseline-docker-compose.yml"  # Docker compose file location
  Note: "DH"
Carol_TC_Config:  # Carol's Traffic Control settings.
  Constraint1:      # Constraint 1, this is the adjustable constraint.
    Type: tbf           # Type of constraint, tbf for token bucket filter.
    Constraint: buffer    # Constraint to adjust, rate in this case.
    Interface: eth0     # Interface to apply the constraint to.
    StartRange: 2048    # Start range of the constraint.
    EndRange: 1        # End range of the constraint.
    Units: kb         # Units of the constraint.
    Steps: 21           # Number of steps to take between the start and end range.
    AddParams: rate 1kbit lat 500ms     # Additional parameters to add to the constraint.
